stages:
  - check_and_test
  - deploy

variables:
  BUILD_PREREQUISITES_CACHE_KEY: "build_pre_${PHP_DC_DOWNLOAD}"

php_5.6:
  stage: check_and_test
  image: registry.gitlab.localdev.cc/infra/php-build-container:5.6
  before_script:
    - curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -o php-dependency-checker
    - chmod +x ./php-dependency-checker
  script:
    - composer install
    - ./php-dependency-checker
    - composer cs-fixer-dry
    - composer run unit-tests
  tags:
    - docker

php_7.4:
  stage: check_and_test
  image: registry.gitlab.localdev.cc/infra/php-build-container:7.4
  before_script:
    - curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -o php-dependency-checker
    - chmod +x ./php-dependency-checker
  script:
    - composer install
    - ./php-dependency-checker
    - composer run unit-tests
  tags:
    - docker

# todo use PHPUnit polyfills for PHP 8 compatibility
#php_8.1:
#  stage: check_and_test
#  image: registry.gitlab.localdev.cc/infra/php-build-container:8.1
#  before_script:
#    - curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -o php-dependency-checker
#    - chmod +x ./php-dependency-checker
#  script:
#    - composer install
#    - ./php-dependency-checker
#    - composer run unit-tests
#  tags:
#    - docker

sync_to_github:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client git
    - mkdir ~/.ssh && chmod 0700 ~/.ssh
    - echo "$GITHUB_PK" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - echo "$GITHUB_HK" > ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts
  script:
    - git remote add github git@github.com:shopgate/connect-integration-sdk-php.git || true
    - git checkout master
    - git pull origin master
    - git push --tags github
    - git push github $CI_COMMIT_REF_NAME:master --force
  tags:
    - docker
  when: manual
  only:
    - tags
