#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';
require __DIR__.'/command/ServiceGenerator.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ServiceGenerator());

$application->run();
